language: go

# Ubuntu 20.04 uses Python 3.6 as the default Python, which we need in the
# integration test scripts.
dist: focal

go:
  - "1.15"

env:
  - GO111MODULE=on

before_install:
  - sudo apt-get install -y graphviz tree
  - curl https://rclone.org/install.sh | sudo bash

before_script:
  - export GOBIN=$GOPATH/bin
  - export PATH=$PATH:$GOBIN

script:
  - make integration-test
