name: build
on: push
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Set environment variables
        shell: bash
        run: |
          export GO111MODULE=on

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: build --snapshot --rm-dist

      - name: Install test dependencies
        shell: bash
        run: |
          sudo apt-get install -y graphviz tree
          curl https://rclone.org/install.sh | sudo bash

      - name: Build and run all tests
        shell: bash
        run: |
          make integration-test
